version: "3.1"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jalal
      MYSQL_DATABASE: testDB
      MYSQL_USER: jalal
      MYSQL_PASSWORD: jalal
    ports:
      - 3306:3306 # make sure you don't have another container running on 3306
    volumes:
      - ./mysql:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
